<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.css">
</head>
<body>

<div class="container">
    <h1>Wallet</h1>
    <div class="panel panel-default">
        <div class="panel-body">
                Account balance
                <b id="accountBalance">0</b><span class="glyphicon glyphicon-btc"></span>
                Transaction count: <b id="transactionCount">0</b>
                Income: <b id="income">0</b> <span class="glyphicon glyphicon-btc"></span>
                Outcome: <b id="outcome">0</b> <span class="glyphicon glyphicon-btc"></span>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-body">
            <form class="form-inline" id="transaction">
                <div class="form-group">
                    <label for="amount">Amount:</label>
                    <input type="number" class="form-control amount">
                </div>
                <div class="form-group">
                    <label for="title">Title:</label>
                    <input type="text" class="form-control title">
                </div>
                <label class="radio-inline"><input type="radio" name="type" value="1">Income</label>
                <label class="radio-inline"><input type="radio" name="type" value="-1">Outcome</label>
                <button type="submit" class="btn btn-primary">Add Transaction</button>
            </form>
        </div>
    </div>
    <table
            id="table"
            class="table table-no-bordered"
            data-toggle="table"
            data-toolbar="#toolbar"
            data-height="428"
            data-detail-view="true"
            data-detail-formatter="detailFormatter">
        <thead>
        <tr>
            <th data-field="transactionId" data-formatter="transactionIdFormatter">#ID</th>
            <th data-field="type" data-formatter="typeFormatter">Type</th>
            <th data-field="amount" data-formatter="moneyFormatter">Amount</th>
            <th data-field="title">Title</th>
            <th data-field="dateTime">DateTime</th>
        </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

<!-- jQuery first, then Tether, then Bootstrap JS. -->
<script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.1/bootstrap-table.min.js"></script>

<script>
    function moneyFormatter(money) {
        return money + '&nbsp;<span class="glyphicon glyphicon-btc"></span>';
    }
    function transactionIdFormatter($transactionId) {
        return '<b>' + $transactionId + '</b>';
    }

    function typeFormatter(type) {
        if (type == 1) {
            return '<span class="glyphicon glyphicon-plus"></span>';
        }

        if (type == -1) {
            return '<span class="glyphicon glyphicon-minus"></span>';
        }
    }
    function detailFormatter(index, row) {
        var html = [];
        var htm = '<form class="editTransaction" id="'+row.transactionId+'">'+
                '<div class="form-group"> <label>Amount:</label>'+
                '<input type="number" min="0.01" step="0.01" class="form-control amount" value="'+row.amount+'"> </div>'+
                '<div class="form-group"> <label>Title:</label> <input type="text" class="form-control title" value="'+row.title+'"> </div>' +
                '<div class="form-group"> <label>DateTime:</label> <input type="text" class="form-control dateTime" value="'+row.dateTime+'"> </div>' +
                '<button type="submit" class="btn btn-default">Save</button>' +
                '</form>';
        html.push(htm);
        return html.join('');
    }

    $(document).on('submit', 'form#transaction', function (e) {
        e.preventDefault();

        var obj = {};
        obj.amount = $("#transaction input.form-control.amount").val();
        obj.title = $("#transaction input.form-control.title").val();
        obj.type = $("#transaction input[name=type]:checked").val();

        console.log(obj.type);
        if (typeof obj.type === "undefined") {
            alert('<b>Select Transaction type </b>');
            return false;
        }

        $.ajax({
            url : "/user/22/transaction",
            type: "POST",
            data: JSON.stringify(obj),
            contentType: "application/json; charset=utf-8",
            dataType   : "json",
            success    : function(response){
                $.get("/user/transaction/list", function(data){
                    $table.bootstrapTable('load',data);
                });
                $.get("/user/22/wallet", function (data) {
                    $("#accountBalance").text(data.accountBalance);
                    $("#transactionCount").text(data.transactionCount);
                });

                $.get("/user/22/transaction/stats", function (data) {
                    $("#income").text(data.income);
                    $("#outcome").text(data.outcome);
                })
            },
            error       : function (response) {
                alert('add transaction error');
            }
        });
    });

    $(document).on('submit', 'form.editTransaction', function(e){
        e.preventDefault();
        var obj = {};
        obj.amount = $("#" + e.target.id + " input.form-control.amount").val();
        obj.title = $("#" + e.target.id + " input.form-control.title").val();
        obj.dateTime = $("#" + e.target.id + " input.form-control.dateTime").val();
        obj.userId = 22;

        $.ajax({
            url : "/transaction/"+e.target.id,
            type: "POST",
            data: JSON.stringify(obj),
            contentType: "application/json; charset=utf-8",
            dataType   : "json",
            success    : function(response){
                $.get("/user/transaction/list", function(data){
                    $table.bootstrapTable('load',data);
                });
                $.get("/user/22/wallet", function (data) {
                    $("#accountBalance").text(data.accountBalance);
                    $("#transactionCount").text(data.transactionCount);
                });
                $.get("/user/22/transaction/stats", function (data) {
                    $("#income").text(data.income);
                    $("#outcome").text(data.outcome);
                })
            },
            error : function (response) {
                alert("edit transaction error")
            }
        });
    });

    $(document).ready(function () {
        $.get("/user/transaction/list", function(data){
            $table.bootstrapTable('load',data);
        });

        $.get("/user/22/wallet", function (data) {
           $("#accountBalance").text(data.accountBalance);
            $("#transactionCount").text(data.transactionCount);
        });

        $.get("/user/22/transaction/stats", function (data) {
            $("#income").text(data.income);
            $("#outcome").text(data.outcome);

        })
    });

    var $table = $('#table'), $button = $('#button'), $load = $('#load');
</script>
</body>
</html>